In [54]:
import json
import collections
import itertools
import os

In [55]:
DATA_DIR = '../nogit/test_data/3q_4g_4blk_data/'
GOOD_DATA_PATH = DATA_DIR + 'good_fidelity/'
BAD_DATA_PATH = DATA_DIR + 'poor_fidelity/'

In [56]:
good_data = []
poor_data = []

for filename in os.listdir(GOOD_DATA_PATH):
    with open(GOOD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        good_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

for filename in os.listdir(BAD_DATA_PATH):
    with open(BAD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        poor_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

print(f"Number of good data samples: {len(good_data)}")
print(f"Number of poor data samples: {len(poor_data)}")

Number of good data samples: 1001
Number of poor data samples: 0


In [57]:
s, c, p, f = good_data[0]
print(type(s))
print(type(c))
print(type(p))
print(type(f))

<class 'int'>
<class 'list'>
<class 'list'>
<class 'float'>


In [58]:
test_good_data = good_data[:1000]
dup_ct = 0
for i, (s1, c1, p1, f1) in enumerate(test_good_data):
    for j, (s2, c2, p2, f2) in enumerate(test_good_data[i + 1:]):
        if all(x == y for x, y in zip(c1, c2)):
            print(f"Duplicate found {i}: {s1} and {i+1+j} : {s2}")
            print(f"Fidelities are \t{f1:.4f} and\t{f2:.4f}")
            # print(f"PQC params are {p1} and {p2}")
            dup_ct += 1

            


Duplicate found 9: 284 and 245 : 952
Fidelities are 	1.0000 and	1.0000
Duplicate found 9: 284 and 615 : 404
Fidelities are 	1.0000 and	1.0000
Duplicate found 9: 284 and 979 : 985
Fidelities are 	1.0000 and	1.0000
Duplicate found 11: 512 and 101 : 524
Fidelities are 	1.0000 and	1.0000
Duplicate found 11: 512 and 837 : 79
Fidelities are 	1.0000 and	1.0000
Duplicate found 27: 553 and 653 : 940
Fidelities are 	1.0000 and	1.0000
Duplicate found 44: 713 and 201 : 99
Fidelities are 	1.0000 and	1.0000
Duplicate found 46: 590 and 82 : 267
Fidelities are 	1.0000 and	1.0000
Duplicate found 46: 590 and 706 : 274
Fidelities are 	1.0000 and	1.0000
Duplicate found 47: 98 and 49 : 986
Fidelities are 	1.0000 and	1.0000
Duplicate found 47: 98 and 407 : 485
Fidelities are 	1.0000 and	1.0000
Duplicate found 47: 98 and 657 : 805
Fidelities are 	1.0000 and	1.0000
Duplicate found 49: 986 and 407 : 485
Fidelities are 	1.0000 and	1.0000
Duplicate found 49: 986 and 657 : 805
Fidelities are 	1.0000 and	1.0000
Du

In [59]:
print(f"Total duplicates found: {dup_ct}")


Total duplicates found: 81


In [91]:
S1 = 858
S2 = 963

In [92]:
print(good_data[S1])

(623, [['h', [0], []], ['h', [0], []], ['h', [0], []], ['h', [2], []]], [[[-0.016251403838396072, -0.06333368271589279, -0.015570607036352158], [0.000381889141863212, -0.00022001523757353425, 0.0002135776012437418], [-0.00013771145313512534, -0.0307456124573946, 6.315996870398521e-05]]], 0.9999998807907104)


In [93]:
print(good_data[S2])

(803, [['h', [0], []], ['h', [0], []], ['h', [0], []], ['h', [2], []]], [[[-0.015408076345920563, -0.0626549944281578, -0.01572054997086525], [-0.0001326031342614442, -0.00011843480751849711, -0.0001187395173474215], [0.00038057161145843565, -0.03163779899477959, -0.00029630219796672463]]], 1.0)


In [94]:
c1 = good_data[S1][1]
c2 = good_data[S2][1]

list(zip(c1, c2))   

[(['h', [0], []], ['h', [0], []]),
 (['h', [0], []], ['h', [0], []]),
 (['h', [0], []], ['h', [0], []]),
 (['h', [2], []], ['h', [2], []])]

In [100]:
import numpy as np
p1 = good_data[S1][2]
p2 = good_data[S2][2]

[print(*p, sep="\n", end="\n***\n") for p in np.round(list(zip(*p1, *p2)), 5)]

[-0.01625 -0.06333 -0.01557]
[-0.01541 -0.06265 -0.01572]
***
[ 0.00038 -0.00022  0.00021]
[-0.00013 -0.00012 -0.00012]
***
[-1.400e-04 -3.075e-02  6.000e-05]
[ 0.00038 -0.03164 -0.0003 ]
***


[None, None, None]

In [96]:
all(x == y for x, y in zip(c1, c2))

True