In [16]:
import json
import collections
import itertools
import os

In [17]:
DATA_DIR = '../nogit/quaternion/uncomp_data/rzrxrz/3q_5g_5blk_data/'
GOOD_DATA_PATH = DATA_DIR + 'good_fidelity/'
BAD_DATA_PATH = DATA_DIR + 'poor_fidelity/'

In [18]:
good_data = []
poor_data = []

for filename in os.listdir(GOOD_DATA_PATH):
    with open(GOOD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        good_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

for filename in os.listdir(BAD_DATA_PATH):
    with open(BAD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        poor_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

print(f"Number of good data samples: {len(good_data)}")
print(f"Number of poor data samples: {len(poor_data)}")

Number of good data samples: 1001
Number of poor data samples: 0


In [19]:
s, c, p, f = good_data[0]
print(type(s))
print(type(c))
print(type(p))
print(type(f))

<class 'int'>
<class 'list'>
<class 'list'>
<class 'float'>


In [20]:
test_good_data = good_data[:1000]
dup_idx = []
for i, (s1, c1, p1, f1) in enumerate(test_good_data):
    for j, (s2, c2, p2, f2) in enumerate(test_good_data[i + 1:]):
        if all(x == y for x, y in zip(c1, c2)):
            print(f"Duplicate found {i}: {s1} and {i+1+j} : {s2}")
            print(f"Fidelities are \t{f1:.4f} and\t{f2:.4f}")
            # print(f"PQC params are {p1} and {p2}")
            dup_idx.append((i, j+i+1))
            


Duplicate found 52: 640 and 683 : 757
Fidelities are 	1.0000 and	1.0000
Duplicate found 71: 41 and 646 : 444
Fidelities are 	1.0000 and	1.0000
Duplicate found 76: 16 and 277 : 934
Fidelities are 	1.0000 and	1.0000
Duplicate found 228: 440 and 703 : 777
Fidelities are 	1.0000 and	1.0000
Duplicate found 390: 217 and 973 : 194
Fidelities are 	1.0000 and	1.0000
Duplicate found 438: 542 and 620 : 541
Fidelities are 	1.0000 and	1.0000
Duplicate found 444: 309 and 701 : 798
Fidelities are 	1.0000 and	1.0000
Duplicate found 507: 218 and 680 : 995
Fidelities are 	1.0000 and	1.0000
Duplicate found 569: 428 and 791 : 382
Fidelities are 	1.0000 and	1.0000
Duplicate found 714: 223 and 737 : 425
Fidelities are 	0.9991 and	0.9991
Duplicate found 731: 599 and 897 : 225
Fidelities are 	1.0000 and	1.0000
Duplicate found 793: 697 and 827 : 567
Fidelities are 	1.0000 and	1.0000


In [21]:
print(f"Total duplicates found: {len(dup_idx)}")


Total duplicates found: 12


In [22]:
S1 = 39
S2 = 135

In [23]:
print(good_data[S1])

(482, [['cx', [2, 1], []], ['h', [0], []], ['h', [2], []], ['x', [0], []], ['cx', [1, 0], []], ['cx', [1, 0], []], ['x', [0], []], ['h', [2], []], ['h', [0], []], ['cx', [2, 1], []]], [[[3.141592264175415, 0.11279206722974777, -3.141592025756836], [3.1415855884552, 0.03140253946185112, -3.1415860652923584], [-0.051605224609375, 0.04870221018791199, -0.011155128479003906]], [[3.141592264175415, 0.031394943594932556, 3.0973851680755615], [-3.141592502593994, 0.09419764578342438, 3.141592264175415], [3.141585111618042, 0.03140253946185112, 3.06152606010437]]], 1.0)


In [24]:
print(good_data[S2])

(7, [['h', [1], []], ['h', [2], []], ['cx', [0, 2], []], ['h', [0], []], ['cx', [0, 1], []], ['cx', [0, 1], []], ['h', [0], []], ['cx', [0, 2], []], ['h', [2], []], ['h', [1], []]], [[[-3.141589403152466, 0.03140253946185112, 3.078819513320923], [-3.141592025756836, 0.4635690152645111, 3.141592264175415], [-3.141592502593994, 0.28616011142730713, 3.141592264175415]], [[-3.141584873199463, 0.031394943594932556, 3.0788156986236572], [3.1415774822235107, 0.031394943594932556, -2.7722084522247314], [3.1415855884552, 0.03138735145330429, -2.949625253677368]]], 1.0)


In [25]:
c1 = good_data[S1][1]
c2 = good_data[S2][1]

list(zip(c1, c2))   

[(['cx', [2, 1], []], ['h', [1], []]),
 (['h', [0], []], ['h', [2], []]),
 (['h', [2], []], ['cx', [0, 2], []]),
 (['x', [0], []], ['h', [0], []]),
 (['cx', [1, 0], []], ['cx', [0, 1], []]),
 (['cx', [1, 0], []], ['cx', [0, 1], []]),
 (['x', [0], []], ['h', [0], []]),
 (['h', [2], []], ['cx', [0, 2], []]),
 (['h', [0], []], ['h', [2], []]),
 (['cx', [2, 1], []], ['h', [1], []])]

In [26]:
import numpy as np
p1 = good_data[S1][2]
p2 = good_data[S2][2]

[print(*p, sep="\n", end="\n***\n") for p in np.round(list(zip(*p1, *p2)), 5)]

[ 3.14159  0.11279 -3.14159]
[3.14159 0.03139 3.09739]
[-3.14159  0.0314   3.07882]
[-3.14158  0.03139  3.07882]
***
[ 3.14159  0.0314  -3.14159]
[-3.14159  0.0942   3.14159]
[-3.14159  0.46357  3.14159]
[ 3.14158  0.03139 -2.77221]
***
[-0.05161  0.0487  -0.01116]
[3.14159 0.0314  3.06153]
[-3.14159  0.28616  3.14159]
[ 3.14159  0.03139 -2.94963]
***


[None, None, None]

In [27]:
print(p1)

[[[3.141592264175415, 0.11279206722974777, -3.141592025756836], [3.1415855884552, 0.03140253946185112, -3.1415860652923584], [-0.051605224609375, 0.04870221018791199, -0.011155128479003906]], [[3.141592264175415, 0.031394943594932556, 3.0973851680755615], [-3.141592502593994, 0.09419764578342438, 3.141592264175415], [3.141585111618042, 0.03140253946185112, 3.06152606010437]]]


In [28]:
print(p2)

[[[-3.141589403152466, 0.03140253946185112, 3.078819513320923], [-3.141592025756836, 0.4635690152645111, 3.141592264175415], [-3.141592502593994, 0.28616011142730713, 3.141592264175415]], [[-3.141584873199463, 0.031394943594932556, 3.0788156986236572], [3.1415774822235107, 0.031394943594932556, -2.7722084522247314], [3.1415855884552, 0.03138735145330429, -2.949625253677368]]]


In [29]:
all(x == y for x, y in zip(c1, c2))

False

In [30]:
for idx1, idx2 in dup_idx:
    pqc1 = good_data[idx1][2]
    pqc2 = good_data[idx2][2]
    for (index1, value1), (index2, value2) in zip(np.ndenumerate(pqc1), np.ndenumerate(pqc2)):
        if abs(value1 - value2) > 1e-3:
            cos1 = np.cos(value1)
            cos2 = np.cos(value2)
            print(f"Difference found at pos {index1}, {index2} between {idx1} and {idx2}: {value1:0.5f} vs {value2:0.5f} (cos: {cos1:0.5f} vs {cos2:0.5f})")

Difference found at pos (0, 0, 0), (0, 0, 0) between 52 and 683: -3.01456 vs -3.11682 (cos: -0.99194 vs -0.99969)
Difference found at pos (0, 0, 1), (0, 0, 1) between 52 and 683: 0.23650 vs 0.04551 (cos: 0.97216 vs 0.99896)
Difference found at pos (0, 0, 2), (0, 0, 2) between 52 and 683: 2.96391 vs 2.94898 (cos: -0.98426 vs -0.98151)
Difference found at pos (0, 1, 0), (0, 1, 0) between 52 and 683: 1.31576 vs 3.10014 (cos: 0.25228 vs -0.99914)
Difference found at pos (0, 1, 1), (0, 1, 1) between 52 and 683: 0.12134 vs 0.17591 (cos: 0.99265 vs 0.98457)
Difference found at pos (0, 1, 2), (0, 1, 2) between 52 and 683: -1.35581 vs -2.86456 (cos: 0.21334 vs -0.96187)
Difference found at pos (0, 2, 0), (0, 2, 0) between 52 and 683: 0.38861 vs -1.64594 (cos: 0.92544 vs -0.07507)
Difference found at pos (0, 2, 1), (0, 2, 1) between 52 and 683: 0.15198 vs 0.11270 (cos: 0.98847 vs 0.99366)
Difference found at pos (0, 2, 2), (0, 2, 2) between 52 and 683: -0.46998 vs 1.48168 (cos: 0.89158 vs 0.0889