In [244]:
import json
import collections
import itertools
import os

In [245]:
DATA_DIR = '../nogit/quaternion/no_uncomp_data/rzrxrz/3q_4g_4blk_data/'
GOOD_DATA_PATH = DATA_DIR + 'good_fidelity/'
BAD_DATA_PATH = DATA_DIR + 'poor_fidelity/'

In [246]:
good_data = []
poor_data = []

for filename in os.listdir(GOOD_DATA_PATH):
    with open(GOOD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        good_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

for filename in os.listdir(BAD_DATA_PATH):
    with open(BAD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        poor_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

print(f"Number of good data samples: {len(good_data)}")
print(f"Number of poor data samples: {len(poor_data)}")

Number of good data samples: 1608
Number of poor data samples: 0


In [247]:
s, c, p, f = good_data[0]
print(type(s))
print(type(c))
print(type(p))
print(type(f))

<class 'int'>
<class 'list'>
<class 'list'>
<class 'float'>


In [248]:
test_good_data = good_data[:1000]
dup_idx = []
for i, (s1, c1, p1, f1) in enumerate(test_good_data):
    for j, (s2, c2, p2, f2) in enumerate(test_good_data[i + 1:]):
        if all(x == y for x, y in zip(c1, c2)):
            print(f"Duplicate found {i}: {s1} and {i+1+j} : {s2}")
            print(f"Fidelities are \t{f1:.4f} and\t{f2:.4f}")
            # print(f"PQC params are {p1} and {p2}")
            dup_idx.append((i, j+i+1))
            


Duplicate found 1: 683 and 617 : 2208
Fidelities are 	1.0000 and	1.0000
Duplicate found 4: 115 and 396 : 2301
Fidelities are 	1.0000 and	1.0000
Duplicate found 5: 1120 and 11 : 2167
Fidelities are 	1.0000 and	1.0000
Duplicate found 10: 953 and 963 : 2421
Fidelities are 	1.0000 and	1.0000
Duplicate found 12: 284 and 377 : 952
Fidelities are 	1.0000 and	1.0000
Duplicate found 15: 512 and 144 : 524
Fidelities are 	1.0000 and	1.0000
Duplicate found 15: 512 and 292 : 1984
Fidelities are 	1.0000 and	1.0000
Duplicate found 23: 338 and 484 : 2136
Fidelities are 	1.0000 and	1.0000
Duplicate found 37: 1136 and 330 : 2330
Fidelities are 	1.0000 and	1.0000
Duplicate found 40: 1970 and 561 : 754
Fidelities are 	1.0000 and	1.0000
Duplicate found 43: 1073 and 556 : 88
Fidelities are 	0.9998 and	0.9998
Duplicate found 45: 251 and 428 : 1700
Fidelities are 	0.9998 and	0.9998
Duplicate found 47: 1321 and 99 : 1878
Fidelities are 	1.0000 and	1.0000
Duplicate found 58: 713 and 317 : 99
Fidelities are 	1.0

In [249]:
print(f"Total duplicates found: {len(dup_idx)}")


Total duplicates found: 88


In [250]:
S1 = 277
S2 = 792

In [251]:
print(good_data[S1])

(17, [['cx', [2, 1], []], ['x', [0], []], ['x', [0], []], ['h', [0], []]], [[[3.1415903568267822, 0.03140253946185112, 3.0787947177886963], [-3.1415915489196777, 0.03140253946185112, 3.1415913105010986], [3.1415889263153076, 0.031394943594932556, -3.1415889263153076]]], 1.0)


In [252]:
print(good_data[S2])

(1112, [['h', [0], []], ['h', [2], []], ['x', [2], []], ['h', [1], []]], [[[3.1415913105010986, 0.03140253946185112, -3.141591787338257], [-3.1415867805480957, 0.031394943594932556, 3.1415865421295166], [-3.1415820121765137, 0.06279942393302917, 3.1415817737579346]]], 1.0)


In [253]:
c1 = good_data[S1][1]
c2 = good_data[S2][1]

list(zip(c1, c2))   

[(['cx', [2, 1], []], ['h', [0], []]),
 (['x', [0], []], ['h', [2], []]),
 (['x', [0], []], ['x', [2], []]),
 (['h', [0], []], ['h', [1], []])]

In [254]:
import numpy as np
p1 = good_data[S1][2]
p2 = good_data[S2][2]

[print(*p, sep="\n", end="\n***\n") for p in np.round(list(zip(*p1, *p2)), 5)]

[3.14159 0.0314  3.07879]
[ 3.14159  0.0314  -3.14159]
***
[-3.14159  0.0314   3.14159]
[-3.14159  0.03139  3.14159]
***
[ 3.14159  0.03139 -3.14159]
[-3.14158  0.0628   3.14158]
***


[None, None, None]

In [255]:
all(x == y for x, y in zip(c1, c2))

False

In [256]:
for idx1, idx2 in dup_idx:
    pqc1 = good_data[idx1][2]
    pqc2 = good_data[idx2][2]
    for (index1, value1), (index2, value2) in zip(np.ndenumerate(pqc1), np.ndenumerate(pqc2)):
        if abs(value1 - value2) > 1e-3:
            print(f"Difference found at pos {index1}, {index2} between {idx1} and {idx2}: {value1:0.5f} vs {value2:0.5f}")

Difference found at pos (0, 0, 0), (0, 0, 0) between 1 and 617: 3.14158 vs -3.14091
Difference found at pos (0, 2, 0), (0, 2, 0) between 1 and 617: -3.14158 vs 3.14131
Difference found at pos (0, 2, 2), (0, 2, 2) between 1 and 617: 3.14159 vs -3.14131
Difference found at pos (0, 0, 0), (0, 0, 0) between 10 and 963: 3.14117 vs -3.14158
Difference found at pos (0, 0, 0), (0, 0, 0) between 12 and 377: -3.14158 vs 3.14159
Difference found at pos (0, 1, 0), (0, 1, 0) between 15 and 144: -3.14159 vs 3.14158
Difference found at pos (0, 1, 2), (0, 1, 2) between 15 and 144: 3.14159 vs -3.14158
Difference found at pos (0, 0, 0), (0, 0, 0) between 23 and 484: 3.14159 vs -3.14159
Difference found at pos (0, 0, 2), (0, 0, 2) between 23 and 484: -3.14159 vs 3.14159
Difference found at pos (0, 1, 0), (0, 1, 0) between 23 and 484: -3.14158 vs 3.14159
Difference found at pos (0, 1, 2), (0, 1, 2) between 23 and 484: 3.14158 vs -3.14159
Difference found at pos (0, 2, 0), (0, 2, 0) between 23 and 484: 3.1