In [223]:
import json
import collections
import itertools
import os

In [224]:
DATA_DIR = '../nogit/uncomp_data/3q_5g_5blk_data/'
GOOD_DATA_PATH = DATA_DIR + 'good_fidelity/'
BAD_DATA_PATH = DATA_DIR + 'poor_fidelity/'

In [225]:
good_data = []
poor_data = []

for filename in os.listdir(GOOD_DATA_PATH):
    with open(GOOD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        good_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

for filename in os.listdir(BAD_DATA_PATH):
    with open(BAD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        poor_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

print(f"Number of good data samples: {len(good_data)}")
print(f"Number of poor data samples: {len(poor_data)}")

Number of good data samples: 1001
Number of poor data samples: 0


In [226]:
s, c, p, f = good_data[0]
print(type(s))
print(type(c))
print(type(p))
print(type(f))

<class 'int'>
<class 'list'>
<class 'list'>
<class 'float'>


In [227]:
test_good_data = good_data[:1000]
dup_idx = []
for i, (s1, c1, p1, f1) in enumerate(test_good_data):
    for j, (s2, c2, p2, f2) in enumerate(test_good_data[i + 1:]):
        if all(x == y for x, y in zip(c1, c2)):
            print(f"Duplicate found {i}: {s1} and {i+1+j} : {s2}")
            print(f"Fidelities are \t{f1:.4f} and\t{f2:.4f}")
            # print(f"PQC params are {p1} and {p2}")
            dup_idx.append((i, j+i+1))
            


Duplicate found 52: 640 and 683 : 757
Fidelities are 	1.0000 and	1.0000
Duplicate found 71: 41 and 646 : 444
Fidelities are 	1.0000 and	1.0000
Duplicate found 76: 16 and 277 : 934
Fidelities are 	1.0000 and	1.0000
Duplicate found 228: 440 and 703 : 777
Fidelities are 	1.0000 and	1.0000
Duplicate found 390: 217 and 973 : 194
Fidelities are 	1.0000 and	1.0000
Duplicate found 438: 542 and 620 : 541
Fidelities are 	1.0000 and	1.0000
Duplicate found 444: 309 and 701 : 798
Fidelities are 	1.0000 and	1.0000
Duplicate found 507: 218 and 680 : 995
Fidelities are 	1.0000 and	1.0000
Duplicate found 569: 428 and 791 : 382
Fidelities are 	1.0000 and	1.0000
Duplicate found 714: 223 and 737 : 425
Fidelities are 	0.9991 and	0.9992
Duplicate found 731: 599 and 897 : 225
Fidelities are 	1.0000 and	1.0000
Duplicate found 793: 697 and 827 : 567
Fidelities are 	1.0000 and	1.0000


In [228]:
print(f"Total duplicates found: {len(dup_idx)}")


Total duplicates found: 12


In [229]:
S1 = 52
S2 = 683

In [230]:
print(good_data[S1])

(640, [['h', [0], []], ['h', [1], []], ['h', [1], []], ['x', [1], []], ['x', [2], []], ['x', [2], []], ['x', [1], []], ['h', [1], []], ['h', [1], []], ['h', [0], []]], [[[-0.3524436950683594, -0.08352184295654297, 0.01719808578491211], [-0.3017387390136719, -0.023859262466430664, -0.04536581039428711], [0.05771493911743164, 0.00856637954711914, -0.0035049915313720703]], [[0.04640793800354004, 0.3224296569824219, 0.01806926727294922], [0.1742537021636963, -0.09601163864135742, -0.03208804130554199], [-0.12048792839050293, 0.008844375610351562, -0.002728700637817383]]], 1.0)


In [231]:
print(good_data[S2])

(757, [['h', [0], []], ['h', [1], []], ['h', [1], []], ['x', [1], []], ['x', [2], []], ['x', [2], []], ['x', [1], []], ['h', [1], []], ['h', [1], []], ['h', [0], []]], [[[-0.07895088195800781, 0.06486344337463379, -0.31284546852111816], [-0.027348756790161133, 0.2233426570892334, -0.08571624755859375], [0.1284794807434082, -0.11944103240966797, 0.25946784019470215]], [[-0.0784904956817627, 0.06519818305969238, -0.3128523826599121], [-0.08185458183288574, 0.16281819343566895, -0.08092164993286133], [-0.1569218635559082, -0.1551666259765625, 0.24011731147766113]]], 1.0)


In [232]:
c1 = good_data[S1][1]
c2 = good_data[S2][1]

list(zip(c1, c2))   

[(['h', [0], []], ['h', [0], []]),
 (['h', [1], []], ['h', [1], []]),
 (['h', [1], []], ['h', [1], []]),
 (['x', [1], []], ['x', [1], []]),
 (['x', [2], []], ['x', [2], []]),
 (['x', [2], []], ['x', [2], []]),
 (['x', [1], []], ['x', [1], []]),
 (['h', [1], []], ['h', [1], []]),
 (['h', [1], []], ['h', [1], []]),
 (['h', [0], []], ['h', [0], []])]

In [233]:
import numpy as np
p1 = good_data[S1][2]
p2 = good_data[S2][2]

[print(*p, sep="\n", end="\n***\n") for p in np.round(list(zip(*p1, *p2)), 5)]

[-0.35244 -0.08352  0.0172 ]
[0.04641 0.32243 0.01807]
[-0.07895  0.06486 -0.31285]
[-0.07849  0.0652  -0.31285]
***
[-0.30174 -0.02386 -0.04537]
[ 0.17425 -0.09601 -0.03209]
[-0.02735  0.22334 -0.08572]
[-0.08185  0.16282 -0.08092]
***
[ 0.05771  0.00857 -0.0035 ]
[-0.12049  0.00884 -0.00273]
[ 0.12848 -0.11944  0.25947]
[-0.15692 -0.15517  0.24012]
***


[None, None, None]

In [236]:
print(p1)

[[[-0.3524436950683594, -0.08352184295654297, 0.01719808578491211], [-0.3017387390136719, -0.023859262466430664, -0.04536581039428711], [0.05771493911743164, 0.00856637954711914, -0.0035049915313720703]], [[0.04640793800354004, 0.3224296569824219, 0.01806926727294922], [0.1742537021636963, -0.09601163864135742, -0.03208804130554199], [-0.12048792839050293, 0.008844375610351562, -0.002728700637817383]]]


In [237]:
print(p2)

[[[-0.07895088195800781, 0.06486344337463379, -0.31284546852111816], [-0.027348756790161133, 0.2233426570892334, -0.08571624755859375], [0.1284794807434082, -0.11944103240966797, 0.25946784019470215]], [[-0.0784904956817627, 0.06519818305969238, -0.3128523826599121], [-0.08185458183288574, 0.16281819343566895, -0.08092164993286133], [-0.1569218635559082, -0.1551666259765625, 0.24011731147766113]]]


In [234]:
all(x == y for x, y in zip(c1, c2))

True

In [235]:
for idx1, idx2 in dup_idx:
    pqc1 = good_data[idx1][2]
    pqc2 = good_data[idx2][2]
    for (index1, value1), (index2, value2) in zip(np.ndenumerate(pqc1), np.ndenumerate(pqc2)):
        if abs(value1 - value2) > 1e-3:
            print(f"Difference found at pos {index1}, {index2} between {idx1} and {idx2}: {value1:0.5f} vs {value2:0.5f}")

Difference found at pos (0, 0, 0), (0, 0, 0) between 52 and 683: -0.35244 vs -0.07895
Difference found at pos (0, 0, 1), (0, 0, 1) between 52 and 683: -0.08352 vs 0.06486
Difference found at pos (0, 0, 2), (0, 0, 2) between 52 and 683: 0.01720 vs -0.31285
Difference found at pos (0, 1, 0), (0, 1, 0) between 52 and 683: -0.30174 vs -0.02735
Difference found at pos (0, 1, 1), (0, 1, 1) between 52 and 683: -0.02386 vs 0.22334
Difference found at pos (0, 1, 2), (0, 1, 2) between 52 and 683: -0.04537 vs -0.08572
Difference found at pos (0, 2, 0), (0, 2, 0) between 52 and 683: 0.05771 vs 0.12848
Difference found at pos (0, 2, 1), (0, 2, 1) between 52 and 683: 0.00857 vs -0.11944
Difference found at pos (0, 2, 2), (0, 2, 2) between 52 and 683: -0.00350 vs 0.25947
Difference found at pos (1, 0, 0), (1, 0, 0) between 52 and 683: 0.04641 vs -0.07849
Difference found at pos (1, 0, 1), (1, 0, 1) between 52 and 683: 0.32243 vs 0.06520
Difference found at pos (1, 0, 2), (1, 0, 2) between 52 and 683: