In [1]:
import json
import collections
import itertools
import os

In [2]:
DATA_DIR = '../nogit/quaternion/uncomp_data/rzrxrz/3q_5g_5blk_data/'
GOOD_DATA_PATH = DATA_DIR + 'good_fidelity/'
BAD_DATA_PATH = DATA_DIR + 'poor_fidelity/'

In [3]:
good_data = []
poor_data = []

for filename in os.listdir(GOOD_DATA_PATH):
    with open(GOOD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        good_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

for filename in os.listdir(BAD_DATA_PATH):
    with open(BAD_DATA_PATH + filename, 'r') as f:
        token_dict = json.load(f)
        poor_data.append((token_dict['seed'], token_dict['base_circuit_tokens'], token_dict['pqc_params'], token_dict['fidelity']))
        f.close()

print(f"Number of good data samples: {len(good_data)}")
print(f"Number of poor data samples: {len(poor_data)}")

Number of good data samples: 1001
Number of poor data samples: 0


In [4]:
s, c, p, f = good_data[0]
print(type(s))
print(type(c))
print(type(p))
print(type(f))

<class 'int'>
<class 'list'>
<class 'list'>
<class 'float'>


In [5]:
test_good_data = good_data[:1000]
dup_idx = []
for i, (s1, c1, p1, f1) in enumerate(test_good_data):
    for j, (s2, c2, p2, f2) in enumerate(test_good_data[i + 1:]):
        if all(x == y for x, y in zip(c1, c2)):
            print(f"Duplicate found {i}: {s1} and {i+1+j} : {s2}")
            print(f"Fidelities are \t{f1:.4f} and\t{f2:.4f}")
            # print(f"PQC params are {p1} and {p2}")
            dup_idx.append((i, j+i+1))
            


Duplicate found 52: 640 and 683 : 757
Fidelities are 	1.0000 and	1.0000
Duplicate found 71: 41 and 646 : 444
Fidelities are 	1.0000 and	1.0000
Duplicate found 76: 16 and 277 : 934
Fidelities are 	1.0000 and	1.0000
Duplicate found 228: 440 and 703 : 777
Fidelities are 	1.0000 and	1.0000
Duplicate found 390: 217 and 973 : 194
Fidelities are 	1.0000 and	1.0000
Duplicate found 438: 542 and 620 : 541
Fidelities are 	1.0000 and	1.0000
Duplicate found 444: 309 and 701 : 798
Fidelities are 	1.0000 and	1.0000
Duplicate found 507: 218 and 680 : 995
Fidelities are 	1.0000 and	1.0000
Duplicate found 569: 428 and 791 : 382
Fidelities are 	1.0000 and	1.0000
Duplicate found 714: 223 and 737 : 425
Fidelities are 	0.9991 and	0.9991
Duplicate found 731: 599 and 897 : 225
Fidelities are 	1.0000 and	1.0000
Duplicate found 793: 697 and 827 : 567
Fidelities are 	1.0000 and	1.0000


In [6]:
print(f"Total duplicates found: {len(dup_idx)}")


Total duplicates found: 12


In [7]:
S1 = 39
S2 = 135

In [8]:
print(good_data[S1])

(482, [['cx', [2, 1], []], ['h', [0], []], ['h', [2], []], ['x', [0], []], ['cx', [1, 0], []], ['cx', [1, 0], []], ['x', [0], []], ['h', [2], []], ['h', [0], []], ['cx', [2, 1], []]], [[[3.1415913105010986, 0.11239375919103622, -3.141592025756836], [-3.141587495803833, 0.03140253946185112, 3.141587495803833], [-0.051728248596191406, 0.048417411744594574, -0.011032581329345703]], [[3.1415913105010986, 0.031394943594932556, 3.0969889163970947], [-3.1415886878967285, 0.09420270472764969, 3.1415884494781494], [-3.1415908336639404, 0.03140253946185112, 3.0617997646331787]]], 1.0)


In [9]:
print(good_data[S2])

(7, [['h', [1], []], ['h', [2], []], ['cx', [0, 2], []], ['h', [0], []], ['cx', [0, 1], []], ['cx', [0, 1], []], ['h', [0], []], ['cx', [0, 2], []], ['h', [2], []], ['h', [1], []]], [[[-3.1415915489196777, 0.031394943594932556, 3.078822374343872], [3.1415913105010986, 0.46375370025634766, -3.1415910720825195], [3.141592264175415, 0.2867923080921173, -3.1415915489196777]], [[-3.141575813293457, 0.03140253946185112, 3.0788071155548096], [3.141573667526245, 0.03140253946185112, -2.772019624710083], [3.141584634780884, 0.03140253946185112, -2.9489922523498535]]], 1.0)


In [10]:
c1 = good_data[S1][1]
c2 = good_data[S2][1]

list(zip(c1, c2))   

[(['cx', [2, 1], []], ['h', [1], []]),
 (['h', [0], []], ['h', [2], []]),
 (['h', [2], []], ['cx', [0, 2], []]),
 (['x', [0], []], ['h', [0], []]),
 (['cx', [1, 0], []], ['cx', [0, 1], []]),
 (['cx', [1, 0], []], ['cx', [0, 1], []]),
 (['x', [0], []], ['h', [0], []]),
 (['h', [2], []], ['cx', [0, 2], []]),
 (['h', [0], []], ['h', [2], []]),
 (['cx', [2, 1], []], ['h', [1], []])]

In [11]:
import numpy as np
p1 = good_data[S1][2]
p2 = good_data[S2][2]

[print(*p, sep="\n", end="\n***\n") for p in np.round(list(zip(*p1, *p2)), 5)]

[ 3.14159  0.11239 -3.14159]
[3.14159 0.03139 3.09699]
[-3.14159  0.03139  3.07882]
[-3.14158  0.0314   3.07881]
***
[-3.14159  0.0314   3.14159]
[-3.14159  0.0942   3.14159]
[ 3.14159  0.46375 -3.14159]
[ 3.14157  0.0314  -2.77202]
***
[-0.05173  0.04842 -0.01103]
[-3.14159  0.0314   3.0618 ]
[ 3.14159  0.28679 -3.14159]
[ 3.14158  0.0314  -2.94899]
***


[None, None, None]

In [12]:
print(p1)

[[[3.1415913105010986, 0.11239375919103622, -3.141592025756836], [-3.141587495803833, 0.03140253946185112, 3.141587495803833], [-0.051728248596191406, 0.048417411744594574, -0.011032581329345703]], [[3.1415913105010986, 0.031394943594932556, 3.0969889163970947], [-3.1415886878967285, 0.09420270472764969, 3.1415884494781494], [-3.1415908336639404, 0.03140253946185112, 3.0617997646331787]]]


In [13]:
print(p2)

[[[-3.1415915489196777, 0.031394943594932556, 3.078822374343872], [3.1415913105010986, 0.46375370025634766, -3.1415910720825195], [3.141592264175415, 0.2867923080921173, -3.1415915489196777]], [[-3.141575813293457, 0.03140253946185112, 3.0788071155548096], [3.141573667526245, 0.03140253946185112, -2.772019624710083], [3.141584634780884, 0.03140253946185112, -2.9489922523498535]]]


In [14]:
all(x == y for x, y in zip(c1, c2))

False

In [15]:
for idx1, idx2 in dup_idx:
    pqc1 = good_data[idx1][2]
    pqc2 = good_data[idx2][2]
    for (index1, value1), (index2, value2) in zip(np.ndenumerate(pqc1), np.ndenumerate(pqc2)):
        if abs(value1 - value2) > 1e-3:
            cos1 = np.cos(value1)
            cos2 = np.cos(value2)
            print(f"Difference found at pos {index1}, {index2} between {idx1} and {idx2}: {value1:0.5f} vs {value2:0.5f} (cos: {cos1:0.5f} vs {cos2:0.5f})")

Difference found at pos (0, 0, 0), (0, 0, 0) between 52 and 683: -3.01407 vs -3.11753 (cos: -0.99188 vs -0.99971)
Difference found at pos (0, 0, 1), (0, 0, 1) between 52 and 683: 0.23792 vs 0.04540 (cos: 0.97183 vs 0.99897)
Difference found at pos (0, 0, 2), (0, 0, 2) between 52 and 683: 2.96345 vs 2.94826 (cos: -0.98417 vs -0.98137)
Difference found at pos (0, 1, 0), (0, 1, 0) between 52 and 683: 1.31414 vs 3.10176 (cos: 0.25385 vs -0.99921)
Difference found at pos (0, 1, 1), (0, 1, 1) between 52 and 683: 0.12266 vs 0.17651 (cos: 0.99249 vs 0.98446)
Difference found at pos (0, 1, 2), (0, 1, 2) between 52 and 683: -1.35481 vs -2.86474 (cos: 0.21432 vs -0.96192)
Difference found at pos (0, 2, 0), (0, 2, 0) between 52 and 683: 0.39057 vs -1.64360 (cos: 0.92469 vs -0.07273)
Difference found at pos (0, 2, 1), (0, 2, 1) between 52 and 683: 0.15211 vs 0.11332 (cos: 0.98845 vs 0.99359)
Difference found at pos (0, 2, 2), (0, 2, 2) between 52 and 683: -0.47206 vs 1.47854 (cos: 0.89063 vs 0.0921