In [28]:
import numpy as np



In [29]:
import sys
sys.path.append('../')

from pqcqec.simulate.statevector import (
    run_circuit_with_state,
    run_many_states,
    create_zero_state,
    create_ones_state,
    build_numba_circuit,
)

from pqcqec.circuits.generate import generate_random_circuit
from pqcqec.circuits.pqc_circuits import list_LEL_ZZ

from pqcqec.noise.builder import add_noise_to_base_ops

In [30]:
NUM_QUBITS = 2
NUM_GATES = 4
NUM_GATE_BLOCKS = 2

# Generate a random circuit
circuit_ops = generate_random_circuit(NUM_QUBITS, NUM_GATES, seed=50, backend='list')
for op in circuit_ops:
    print(op)

('h', [1], [])
('z', [1], [])
('cx', [0, 1], [])
('z', [0], [])


In [31]:
ideal_numba_ops = build_numba_circuit(circuit_ops)
printable_ideal_ops = list(zip(*ideal_numba_ops))
for op in printable_ideal_ops:
    print(np.array(op)) 

[ 3.  1. -1.  0.]
[ 2.  1. -1.  0.]
[7. 0. 1. 0.]
[ 2.  0. -1.  0.]


In [32]:

x_noise = np.ones((NUM_GATES,), dtype=np.float32) * 0.1
z_noise = np.ones((NUM_GATES,), dtype=np.float32) * 0.1

noisy_circuit_ops = add_noise_to_base_ops(circuit_ops, x_noise, z_noise)

for op in noisy_circuit_ops:
    print(op)
    

('h', [1], [])
('rx', [1], [np.float32(0.1)])
('rz', [1], [np.float32(0.1)])
('z', [1], [])
('rx', [1], [np.float32(0.1)])
('rz', [1], [np.float32(0.1)])
('cx', [0, 1], [])
('rx', [0], [np.float32(0.1)])
('rz', [0], [np.float32(0.1)])
('rx', [1], [np.float32(0.1)])
('rz', [1], [np.float32(0.1)])
('z', [0], [])
('rx', [0], [np.float32(0.1)])
('rz', [0], [np.float32(0.1)])


In [33]:
noisy_numba_ops = build_numba_circuit(noisy_circuit_ops)

printable_noisy_numba_ops = list(zip(*noisy_numba_ops))
for op in printable_noisy_numba_ops:
    print(np.array(op)) 

[ 3.  1. -1.  0.]
[ 4.   1.  -1.   0.1]
[ 6.   1.  -1.   0.1]
[ 2.  1. -1.  0.]
[ 4.   1.  -1.   0.1]
[ 6.   1.  -1.   0.1]
[7. 0. 1. 0.]
[ 4.   0.  -1.   0.1]
[ 6.   0.  -1.   0.1]
[ 4.   1.  -1.   0.1]
[ 6.   1.  -1.   0.1]
[ 2.  0. -1.  0.]
[ 4.   0.  -1.   0.1]
[ 6.   0.  -1.   0.1]


In [34]:
gate_ids, wire1s, wire2s, params = ideal_numba_ops


In [35]:
initial_state = create_zero_state(NUM_QUBITS)
final_state = run_circuit_with_state(initial_state, NUM_QUBITS, gate_ids, wire1s, wire2s, params)
print("Final state from ideal circuit:")
print(final_state)
# run_many_states(NUM_QUBITS, gate_ids, wire1s, wire2s, params) 

Final state from ideal circuit:
[ 0.70710677+0.j -0.70710677+0.j  0.        -0.j -0.        +0.j]


In [36]:
initial_state = create_ones_state(NUM_QUBITS)
final_state = run_circuit_with_state(initial_state, NUM_QUBITS, gate_ids, wire1s, wire2s, params)
print("Final state from ideal circuit:")
print(final_state)
# run_many_states(NUM_QUBITS, gate_ids, wire1s, wire2s, params) 

Final state from ideal circuit:
[ 0.        +0.j -0.        +0.j -0.70710677+0.j -0.70710677+0.j]
